### ISSUE TITLE
Test "should handle large payloads with udp" fails with payload ~> 600

### ISSUE THREAD

**Issue by florianb** [fed135/Kalm#40]
The default test fails on my Mac.

    1) should handle large payloads with udp

    1) Integration tests Testing udp adapter should handle large payloads with udp:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

After fiddling around i was able to make it work by lowering the payload-size of the test to `while(largePayload.length < 600)`.

---
    ProductName:	Mac OS X
    ProductVersion:	10.11.6
    BuildVersion:	15G1212

**Comment by fed135** [comment]
Thanks for the issue, and sorry for the delay! I definitely need a more robust system to test this rather than a timebox. 

Slower machines, or machines under load will end up busting the default timeout for this test. The easy patch is to either increase the timeout, or reduce the amount of data transferred (like you did), but the best system would be to let it run for as long as it needs to and just catch errors (maybe with chai-as-promised).

I'm pretty swamped lately (since I'm focusing on Kalm v2) - but I accept pull requests if you want to implement it ;)
